"""Public global-search contracts, matching, and coordination."""

from docking.search.coordinator import (
    ProviderError,
    SearchCancellation,
    SearchCancelledError,
    SearchCoordinator,
    SearchProvider,
    SearchRequest,
    SearchSnapshot,
    preserve_selected_identity,
)
from docking.search.intents import (
    CANONICAL_QUERY_KEYWORDS,
    QueryIntent,
    QueryIntentKind,
    complete_query_keyword,
    parse_query_intent,
)
from docking.search.matcher import (
    MATCH_QUALITY_LIMIT,
    SOURCE_BOOST_LIMIT,
    STATE_BOOST_LIMIT,
    TIER_BASE_SCORE,
    MatchTier,
    TextMatch,
    best_match,
    match_text,
    normalize_search_text,
    score_match,
)
from docking.search.types import (
    SearchAction,
    SearchBatch,
    SearchBatchKind,
    SearchIdentity,
    SearchPreview,
    SearchQuery,
    SearchResult,
)
from docking.search.usage import SearchUsageStore, UsageRecord

__all__ = [
    "CANONICAL_QUERY_KEYWORDS",
    "MATCH_QUALITY_LIMIT",
    "SOURCE_BOOST_LIMIT",
    "STATE_BOOST_LIMIT",
    "TIER_BASE_SCORE",
    "MatchTier",
    "ProviderError",
    "QueryIntent",
    "QueryIntentKind",
    "SearchAction",
    "SearchBatch",
    "SearchBatchKind",
    "SearchCancellation",
    "SearchCancelledError",
    "SearchCoordinator",
    "SearchIdentity",
    "SearchPreview",
    "SearchProvider",
    "SearchQuery",
    "SearchRequest",
    "SearchResult",
    "SearchSnapshot",
    "SearchUsageStore",
    "TextMatch",
    "UsageRecord",
    "best_match",
    "complete_query_keyword",
    "match_text",
    "normalize_search_text",
    "parse_query_intent",
    "preserve_selected_identity",
    "score_match",
]
