name: docking
title: Docking
base: core22
version: "0.1.3"
summary: Feature-rich Linux dock in Python with GTK 3 and Cairo
description: |
  A lightweight, feature-rich dock for Linux written in Python with GTK 3 and Cairo.
  Inspired by Plank and Cairo-Dock, it provides pinned launchers, window
  indicators, previews, autohide, drag-and-drop, and an extensible
  applet system.
contact: https://github.com/edumucelli/docking/issues
license: GPL-3.0-or-later
issues: https://github.com/edumucelli/docking/issues
source-code: https://github.com/edumucelli/docking
website: https://github.com/edumucelli/docking
grade: stable
confinement: devmode

apps:
  docking:
    command: bin/docking
    desktop: usr/share/applications/org.docking.Docking.desktop
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - network
      - network-manager
      - audio-playback
      - home

parts:
  docking:
    plugin: python
    source: ../..
    build-packages:
      - pkg-config
      - libcairo2-dev
      - libgirepository1.0-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - gir1.2-gtk-3.0
      - gir1.2-wnck-3.0
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-pango-1.0
      - gir1.2-nm-1.0
      - gir1.2-gstreamer-1.0
      - librsvg2-common
      - ca-certificates
    override-build: |
      craftctl default
      desktop_file="${CRAFT_PART_INSTALL}/usr/share/applications/org.docking.Docking.desktop"
      install -d "$(dirname "${desktop_file}")"
      printf '%s\n' \
        '[Desktop Entry]' \
        'Type=Application' \
        'Name=Docking' \
        'Comment=A lightweight, feature-rich dock for Linux written in Python with GTK 3 and Cairo' \
        'Exec=docking' \
        'Icon=docking' \
        'Categories=Utility;System;' \
        'Terminal=false' \
        'StartupNotify=false' \
        'X-GNOME-Autostart-enabled=false' \
        > "${desktop_file}"

      if [ -f images/docking.png ]; then
        install -Dm644 images/docking.png \
          "${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/512x512/apps/org.docking.Docking.png"
        install -Dm644 images/docking.png \
          "${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/512x512/apps/docking.png"
      else
        echo "Required icon not found: images/docking.png"
        pwd
        ls -la
        exit 1
      fi
