name: docking
base: core22
version: "0.1.1"
summary: Lightweight Linux dock inspired by Plank and Cairo-Dock
description: |
  Docking is a lightweight, feature-rich dock for Linux written in Python
  with GTK 3 and Cairo. It provides pinned launchers, window indicators,
  previews, autohide, drag-and-drop, and an extensible applet system.
grade: stable
confinement: devmode

apps:
  docking:
    command: bin/docking
    desktop: usr/share/applications/org.docking.Docking.desktop
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - network
      - network-manager
      - audio-playback
      - home

parts:
  docking:
    plugin: python
    source: ../..
    build-packages:
      - pkg-config
      - libcairo2-dev
      - libgirepository1.0-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - gir1.2-gtk-3.0
      - gir1.2-wnck-3.0
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-pango-1.0
      - gir1.2-nm-1.0
      - gir1.2-gstreamer-1.0
      - librsvg2-common
      - ca-certificates
    override-build: |
      craftctl default
      desktop_src=""
      icons_src=""
      if [ -f packaging/deb/org.docking.Docking.desktop ]; then
        desktop_src="packaging/deb/org.docking.Docking.desktop"
        icons_src="packaging/deb/icons/hicolor"
      elif [ -f debian/org.docking.Docking.desktop ]; then
        desktop_src="debian/org.docking.Docking.desktop"
        icons_src="debian/icons/hicolor"
      else
        echo "Desktop file source not found in expected locations."
        pwd
        ls -la
        exit 1
      fi

      install -Dm644 "${desktop_src}" \
        "${CRAFT_PART_INSTALL}/usr/share/applications/org.docking.Docking.desktop"
      mkdir -p "${CRAFT_PART_INSTALL}/usr/share/icons"
      cp -r "${icons_src}" "${CRAFT_PART_INSTALL}/usr/share/icons/"
