# This file has been autogenerated by the pywayland scanner
# ruff: noqa

# Copyright © 2022 Vaxry
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from ..wlr_foreign_toplevel_management_unstable_v1 import ZwlrForeignToplevelHandleV1
from .hyprland_toplevel_export_frame_v1 import HyprlandToplevelExportFrameV1


class HyprlandToplevelExportManagerV1(Interface):
    """Manager to inform clients and begin capturing

    This object is a manager which offers requests to start capturing from a
    source.
    """

    name = "hyprland_toplevel_export_manager_v1"
    version = 2


class HyprlandToplevelExportManagerV1Proxy(Proxy[HyprlandToplevelExportManagerV1]):
    interface = HyprlandToplevelExportManagerV1

    @HyprlandToplevelExportManagerV1.request(
        Argument(ArgumentType.NewId, interface=HyprlandToplevelExportFrameV1),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Uint),
    )
    def capture_toplevel(
        self, overlay_cursor: int, handle: int
    ) -> Proxy[HyprlandToplevelExportFrameV1]:
        """Capture a toplevel

        Capture the next frame of a toplevel. (window)

        The captured frame will not contain any server-side decorations and
        will ignore the compositor-set geometry, like e.g. rounded corners.

        It will contain all the subsurfaces and popups, however the latter will
        be clipped to the geometry of the base surface.

        The handle parameter refers to the address of the window as seen in
        `hyprctl clients`. For example, for d161e7b0 it would be 3512854448.

        :param overlay_cursor:
            composite cursor onto the frame
        :type overlay_cursor:
            `ArgumentType.Int`
        :param handle:
            the handle of the toplevel (window) to be captured
        :type handle:
            `ArgumentType.Uint`
        :returns:
            :class:`~pywayland.protocol.hyprland_toplevel_export_v1.HyprlandToplevelExportFrameV1`
        """
        frame = self._marshal_constructor(
            0, HyprlandToplevelExportFrameV1, overlay_cursor, handle
        )
        return frame

    @HyprlandToplevelExportManagerV1.request()
    def destroy(self) -> None:
        """Destroy the manager

        All objects created by the manager will still remain valid, until their
        appropriate destroy request has been called.
        """
        self._marshal(1)
        self._destroy()

    @HyprlandToplevelExportManagerV1.request(
        Argument(ArgumentType.NewId, interface=HyprlandToplevelExportFrameV1),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Object, interface=ZwlrForeignToplevelHandleV1),
        version=2,
    )
    def capture_toplevel_with_wlr_toplevel_handle(
        self, overlay_cursor: int, handle: ZwlrForeignToplevelHandleV1
    ) -> Proxy[HyprlandToplevelExportFrameV1]:
        """Capture a toplevel

        Same as capture_toplevel, but with a
        :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`
        handle.

        :param overlay_cursor:
            composite cursor onto the frame
        :type overlay_cursor:
            `ArgumentType.Int`
        :param handle:
            the
            :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`
            handle of the toplevel to be captured
        :type handle:
            :class:`~pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1.ZwlrForeignToplevelHandleV1`
        :returns:
            :class:`~pywayland.protocol.hyprland_toplevel_export_v1.HyprlandToplevelExportFrameV1`
        """
        frame = self._marshal_constructor(
            2, HyprlandToplevelExportFrameV1, overlay_cursor, handle
        )
        return frame


class HyprlandToplevelExportManagerV1Resource(Resource):
    interface = HyprlandToplevelExportManagerV1


class HyprlandToplevelExportManagerV1Global(Global):
    interface = HyprlandToplevelExportManagerV1


HyprlandToplevelExportManagerV1._gen_c()
HyprlandToplevelExportManagerV1.proxy_class = HyprlandToplevelExportManagerV1Proxy
HyprlandToplevelExportManagerV1.resource_class = HyprlandToplevelExportManagerV1Resource
HyprlandToplevelExportManagerV1.global_class = HyprlandToplevelExportManagerV1Global
