# This file has been autogenerated by the pywayland scanner
# ruff: noqa

# Copyright © 2018 Simon Ser
# Copyright © 2019 Andri Yngvason
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from pywayland.protocol.wayland import WlBuffer


class ZwlrScreencopyFrameV1(Interface):
    """A frame ready for copy

    This object represents a single frame.

    When created, a series of buffer events will be sent, each representing a
    supported buffer type. The "buffer_done" event is sent afterwards to
    indicate that all supported buffer types have been enumerated. The client
    will then be able to send a "copy" request. If the capture is successful,
    the compositor will send a "flags" followed by a "ready" event.

    For objects version 2 or lower, wl_shm buffers are always supported, ie.
    the "buffer" event is guaranteed to be sent.

    If the capture failed, the "failed" event is sent. This can happen anytime
    before the "ready" event.

    Once either a "ready" or a "failed" event is received, the client should
    destroy the frame.
    """

    name = "zwlr_screencopy_frame_v1"
    version = 3

    class error(enum.IntEnum):
        already_used = 0
        invalid_buffer = 1

    class flags(enum.IntFlag):
        y_invert = 1


class ZwlrScreencopyFrameV1Proxy(Proxy[ZwlrScreencopyFrameV1]):
    interface = ZwlrScreencopyFrameV1

    @ZwlrScreencopyFrameV1.request(
        Argument(ArgumentType.Object, interface=WlBuffer),
    )
    def copy(self, buffer: WlBuffer) -> None:
        """Copy the frame to the supplied buffer."""
        self._marshal(0, buffer)

    @ZwlrScreencopyFrameV1.request()
    def destroy(self) -> None:
        """Delete this object, used or not."""
        self._marshal(1)
        self._destroy()

    @ZwlrScreencopyFrameV1.request(
        Argument(ArgumentType.Object, interface=WlBuffer),
        version=2,
    )
    def copy_with_damage(self, buffer: WlBuffer) -> None:
        """Copy the frame when it's damaged."""
        self._marshal(2, buffer)


class ZwlrScreencopyFrameV1Resource(Resource):
    interface = ZwlrScreencopyFrameV1

    @ZwlrScreencopyFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def buffer(self, format: int, width: int, height: int, stride: int) -> None:
        """wl_shm buffer information."""
        self._post_event(0, format, width, height, stride)

    @ZwlrScreencopyFrameV1.event(
        Argument(ArgumentType.Uint),
    )
    def flags(self, flags: int) -> None:
        """Frame flags."""
        self._post_event(1, flags)

    @ZwlrScreencopyFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def ready(self, tv_sec_hi: int, tv_sec_lo: int, tv_nsec: int) -> None:
        """Indicates frame is available for reading."""
        self._post_event(2, tv_sec_hi, tv_sec_lo, tv_nsec)

    @ZwlrScreencopyFrameV1.event()
    def failed(self) -> None:
        """Frame copy failed."""
        self._post_event(3)

    @ZwlrScreencopyFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        version=2,
    )
    def damage(self, x: int, y: int, width: int, height: int) -> None:
        """Carries the coordinates of the damaged region."""
        self._post_event(4, x, y, width, height)

    @ZwlrScreencopyFrameV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        version=3,
    )
    def linux_dmabuf(self, format: int, width: int, height: int) -> None:
        """Linux-dmabuf buffer information."""
        self._post_event(5, format, width, height)

    @ZwlrScreencopyFrameV1.event(version=3)
    def buffer_done(self) -> None:
        """All buffer types reported."""
        self._post_event(6)


class ZwlrScreencopyFrameV1Global(Global):
    interface = ZwlrScreencopyFrameV1


ZwlrScreencopyFrameV1._gen_c()
ZwlrScreencopyFrameV1.proxy_class = ZwlrScreencopyFrameV1Proxy
ZwlrScreencopyFrameV1.resource_class = ZwlrScreencopyFrameV1Resource
ZwlrScreencopyFrameV1.global_class = ZwlrScreencopyFrameV1Global
